name: update-rss-feeds
run-name: Update RSS feeds
on:
  schedule:
    # Run every 30 minutes. My RSS feed reader refreshes every 30 minutes, so
    # this will result in a maximum 1 hour delay between a new item being posted
    # and it appearing in my RSS reader.
    - cron: '*/30 * * * *'
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Don't deploy updated feeds (dry run)"
        type: boolean

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: Bogdanp/setup-racket@v1.11
        with:
          version: '8.15'
      - run: mkdir _site
      - run: racket ../main.rkt
        working-directory: _site
      - uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: _site
      - uses: actions/upload-pages-artifact@v3
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ !inputs.dry_run }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
  # keepalive:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     actions: write
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: gautamkrishnar/keepalive-workflow@v2
